Repository jupyterhub/dockerspawner, pull requests merged in 2025-02, with the labels that each got.

#510 Document c.DockerSpawner.mounts
  docs/source/data-persistence.md
Labels: documentation

#526 support for bind propagation
  dockerspawner/dockerspawner.py
  dockerspawner/systemuserspawner.py
  tests/volumes_test.py
Labels: new

#528 pre-commit autoupdate
  .gitignore
  .pre-commit-config.yaml
  dockerspawner/dockerspawner.py
  dockerspawner/swarmspawner.py
  tests/conftest.py
  tests/test_dockerspawner.py
  tests/test_swarmspawner.py
  tests/test_systemuserspawner.py
  tests/volumes_test.py
Labels: maintenance

#529 update test versions in ci
  .github/workflows/test.yaml
Labels: maintenance

#530 require Python 3.9, jupyterhub 4, unpin pytest-asyncio
  .github/workflows/test.yaml
  README.md
  dev-requirements.txt
  pyproject.toml
  requirements.txt
  setup.py
  tests/conftest.py
Labels: breaking

#531 update some test dependencies
  dev-requirements.txt
  tests/conftest.py
Labels: maintenance

#532 changelog for 14.0
  dockerspawner/systemuserspawner.py
  docs/source/changelog.md
Labels: documentation
